"""widen period columns to 10 for MMM-YYYY

Revision ID: 051a25aaf4eb
Revises: e63b54c436f6
Create Date: 2026-07-20 14:15:45.148746
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '051a25aaf4eb'
down_revision: Union[str, None] = 'e63b54c436f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('basis_allocation', 'period',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('basis_fte', 'period',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('basis_rev', 'period',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('distribution', 'period',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('distribution_run', 'period',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('distribution_run', 'period',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=True)
    op.alter_column('distribution', 'period',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=True)
    op.alter_column('basis_rev', 'period',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=False)
    op.alter_column('basis_fte', 'period',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=False)
    op.alter_column('basis_allocation', 'period',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=False)
    # ### end Alembic commands ###
