"""add gl_entry fact table

Revision ID: 2c2b38d26fd7
Revises: 051a25aaf4eb
Create Date: 2026-07-20 14:28:53.581415
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c2b38d26fd7'
down_revision: Union[str, None] = '051a25aaf4eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gl_entry',
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('ref_no', sa.String(length=100), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('dept', sa.String(length=200), nullable=True),
    sa.Column('project', sa.String(length=200), nullable=True),
    sa.Column('curr', sa.String(length=10), nullable=True),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('account_code', sa.String(length=50), nullable=True),
    sa.Column('account_name', sa.String(length=200), nullable=True),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gl_entry_account_code'), 'gl_entry', ['account_code'], unique=False)
    op.create_index(op.f('ix_gl_entry_account_name'), 'gl_entry', ['account_name'], unique=False)
    op.create_index(op.f('ix_gl_entry_date'), 'gl_entry', ['date'], unique=False)
    op.create_index(op.f('ix_gl_entry_dept'), 'gl_entry', ['dept'], unique=False)
    op.create_index(op.f('ix_gl_entry_period'), 'gl_entry', ['period'], unique=False)
    op.create_index(op.f('ix_gl_entry_ref_no'), 'gl_entry', ['ref_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gl_entry_ref_no'), table_name='gl_entry')
    op.drop_index(op.f('ix_gl_entry_period'), table_name='gl_entry')
    op.drop_index(op.f('ix_gl_entry_dept'), table_name='gl_entry')
    op.drop_index(op.f('ix_gl_entry_date'), table_name='gl_entry')
    op.drop_index(op.f('ix_gl_entry_account_name'), table_name='gl_entry')
    op.drop_index(op.f('ix_gl_entry_account_code'), table_name='gl_entry')
    op.drop_table('gl_entry')
    # ### end Alembic commands ###
