"""add period_close lock table

Revision ID: 4cd9c762e50d
Revises: e3b1a33685a6
Create Date: 2026-07-20 15:31:44.360614
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd9c762e50d'
down_revision: Union[str, None] = 'e3b1a33685a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period_close',
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('period_close')
    # ### end Alembic commands ###
