"""create cost distribution tables

Revision ID: 554dd0ae023e
Revises: 
Create Date: 2026-07-20 12:36:09.668305
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '554dd0ae023e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distribution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('gl_line_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('ref_no', sa.String(length=100), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('account_name', sa.String(length=200), nullable=True),
    sa.Column('account', sa.String(length=260), nullable=True),
    sa.Column('reporting_account_name', sa.String(length=200), nullable=True),
    sa.Column('dept', sa.String(length=200), nullable=True),
    sa.Column('new_dept', sa.String(length=200), nullable=True),
    sa.Column('div', sa.String(length=200), nullable=True),
    sa.Column('pc', sa.String(length=200), nullable=True),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('allocation', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('method', sa.String(length=100), nullable=True),
    sa.Column('distribution_and_allocation', sa.String(length=300), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distribution_code'), 'distribution', ['code'], unique=False)
    op.create_index(op.f('ix_distribution_date'), 'distribution', ['date'], unique=False)
    op.create_index(op.f('ix_distribution_dept'), 'distribution', ['dept'], unique=False)
    op.create_index(op.f('ix_distribution_div'), 'distribution', ['div'], unique=False)
    op.create_index(op.f('ix_distribution_gl_line_id'), 'distribution', ['gl_line_id'], unique=False)
    op.create_index(op.f('ix_distribution_method'), 'distribution', ['method'], unique=False)
    op.create_index(op.f('ix_distribution_new_dept'), 'distribution', ['new_dept'], unique=False)
    op.create_index(op.f('ix_distribution_pc'), 'distribution', ['pc'], unique=False)
    op.create_index(op.f('ix_distribution_ref_no'), 'distribution', ['ref_no'], unique=False)
    op.create_index(op.f('ix_distribution_run_id'), 'distribution', ['run_id'], unique=False)
    op.create_index(op.f('ix_distribution_type'), 'distribution', ['type'], unique=False)
    op.create_table('distribution_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('source_total', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('allocated_total', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('variance', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('n_gl_lines', sa.Integer(), nullable=True),
    sa.Column('n_output_rows', sa.Integer(), nullable=True),
    sa.Column('n_direct', sa.Integer(), nullable=True),
    sa.Column('n_distributed', sa.Integer(), nullable=True),
    sa.Column('n_rejects', sa.Integer(), nullable=True),
    sa.Column('recompute_basis', sa.Integer(), nullable=True),
    sa.Column('input_path', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distribution_run_run_at'), 'distribution_run', ['run_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_distribution_run_run_at'), table_name='distribution_run')
    op.drop_table('distribution_run')
    op.drop_index(op.f('ix_distribution_type'), table_name='distribution')
    op.drop_index(op.f('ix_distribution_run_id'), table_name='distribution')
    op.drop_index(op.f('ix_distribution_ref_no'), table_name='distribution')
    op.drop_index(op.f('ix_distribution_pc'), table_name='distribution')
    op.drop_index(op.f('ix_distribution_new_dept'), table_name='distribution')
    op.drop_index(op.f('ix_distribution_method'), table_name='distribution')
    op.drop_index(op.f('ix_distribution_gl_line_id'), table_name='distribution')
    op.drop_index(op.f('ix_distribution_div'), table_name='distribution')
    op.drop_index(op.f('ix_distribution_dept'), table_name='distribution')
    op.drop_index(op.f('ix_distribution_date'), table_name='distribution')
    op.drop_index(op.f('ix_distribution_code'), table_name='distribution')
    op.drop_table('distribution')
    # ### end Alembic commands ###
