"""widen gl_entry amount precision

Revision ID: e3b1a33685a6
Revises: 2c2b38d26fd7
Create Date: 2026-07-20 14:32:35.139619
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e3b1a33685a6'
down_revision: Union[str, None] = '2c2b38d26fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gl_entry', 'debit',
               existing_type=mysql.DECIMAL(precision=18, scale=2),
               type_=sa.Numeric(precision=28, scale=12),
               existing_nullable=True)
    op.alter_column('gl_entry', 'credit',
               existing_type=mysql.DECIMAL(precision=18, scale=2),
               type_=sa.Numeric(precision=28, scale=12),
               existing_nullable=True)
    op.alter_column('gl_entry', 'balance',
               existing_type=mysql.DECIMAL(precision=18, scale=2),
               type_=sa.Numeric(precision=28, scale=12),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gl_entry', 'balance',
               existing_type=sa.Numeric(precision=28, scale=12),
               type_=mysql.DECIMAL(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('gl_entry', 'credit',
               existing_type=sa.Numeric(precision=28, scale=12),
               type_=mysql.DECIMAL(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('gl_entry', 'debit',
               existing_type=sa.Numeric(precision=28, scale=12),
               type_=mysql.DECIMAL(precision=18, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
