"""widen basis percentage precision to 30,20

Revision ID: e4b746dd9e64
Revises: fd8f7d5d957d
Create Date: 2026-07-20 13:36:59.500191
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e4b746dd9e64'
down_revision: Union[str, None] = 'fd8f7d5d957d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('basis_allocation', 'percentage',
               existing_type=mysql.DECIMAL(precision=18, scale=9),
               type_=sa.Numeric(precision=30, scale=20),
               existing_nullable=True)
    op.alter_column('basis_rev', 'pct_certification_services',
               existing_type=mysql.DECIMAL(precision=18, scale=9),
               type_=sa.Numeric(precision=30, scale=20),
               existing_nullable=True)
    op.alter_column('basis_rev', 'pct_ho',
               existing_type=mysql.DECIMAL(precision=18, scale=9),
               type_=sa.Numeric(precision=30, scale=20),
               existing_nullable=True)
    op.alter_column('basis_rev', 'pct_all',
               existing_type=mysql.DECIMAL(precision=18, scale=9),
               type_=sa.Numeric(precision=30, scale=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('basis_rev', 'pct_all',
               existing_type=sa.Numeric(precision=30, scale=20),
               type_=mysql.DECIMAL(precision=18, scale=9),
               existing_nullable=True)
    op.alter_column('basis_rev', 'pct_ho',
               existing_type=sa.Numeric(precision=30, scale=20),
               type_=mysql.DECIMAL(precision=18, scale=9),
               existing_nullable=True)
    op.alter_column('basis_rev', 'pct_certification_services',
               existing_type=sa.Numeric(precision=30, scale=20),
               type_=mysql.DECIMAL(precision=18, scale=9),
               existing_nullable=True)
    op.alter_column('basis_allocation', 'percentage',
               existing_type=sa.Numeric(precision=30, scale=20),
               type_=mysql.DECIMAL(precision=18, scale=9),
               existing_nullable=True)
    # ### end Alembic commands ###
