"""drop period from policy basis tables pc coa logic

Revision ID: e63b54c436f6
Revises: e4b746dd9e64
Create Date: 2026-07-20 13:55:37.511252
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e63b54c436f6'
down_revision: Union[str, None] = 'e4b746dd9e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_basis_coa_period'), table_name='basis_coa')
    op.drop_column('basis_coa', 'period')
    op.drop_index(op.f('ix_basis_logic_period'), table_name='basis_logic')
    op.drop_column('basis_logic', 'period')
    op.drop_index(op.f('ix_basis_pc_period'), table_name='basis_pc')
    op.drop_column('basis_pc', 'period')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basis_pc', sa.Column('period', mysql.VARCHAR(length=7), nullable=False))
    op.create_index(op.f('ix_basis_pc_period'), 'basis_pc', ['period'], unique=False)
    op.add_column('basis_logic', sa.Column('period', mysql.VARCHAR(length=7), nullable=False))
    op.create_index(op.f('ix_basis_logic_period'), 'basis_logic', ['period'], unique=False)
    op.add_column('basis_coa', sa.Column('period', mysql.VARCHAR(length=7), nullable=False))
    op.create_index(op.f('ix_basis_coa_period'), 'basis_coa', ['period'], unique=False)
    # ### end Alembic commands ###
