"""add editable monthly basis tables and period

Revision ID: fd8f7d5d957d
Revises: 554dd0ae023e
Create Date: 2026-07-20 13:32:43.263952
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8f7d5d957d'
down_revision: Union[str, None] = '554dd0ae023e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basis_allocation',
    sa.Column('distribution', sa.String(length=100), nullable=True),
    sa.Column('account_name', sa.String(length=200), nullable=True),
    sa.Column('new_dept', sa.String(length=200), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=18, scale=9), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basis_allocation_account_name'), 'basis_allocation', ['account_name'], unique=False)
    op.create_index(op.f('ix_basis_allocation_distribution'), 'basis_allocation', ['distribution'], unique=False)
    op.create_index(op.f('ix_basis_allocation_new_dept'), 'basis_allocation', ['new_dept'], unique=False)
    op.create_index(op.f('ix_basis_allocation_period'), 'basis_allocation', ['period'], unique=False)
    op.create_table('basis_coa',
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('account_name', sa.String(length=200), nullable=True),
    sa.Column('reporting_line', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basis_coa_code'), 'basis_coa', ['code'], unique=False)
    op.create_index(op.f('ix_basis_coa_period'), 'basis_coa', ['period'], unique=False)
    op.create_table('basis_fte',
    sa.Column('fte', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('hc', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('employee_no', sa.String(length=50), nullable=True),
    sa.Column('dept', sa.String(length=200), nullable=True),
    sa.Column('div', sa.String(length=200), nullable=True),
    sa.Column('pc', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('location_detail', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basis_fte_dept'), 'basis_fte', ['dept'], unique=False)
    op.create_index(op.f('ix_basis_fte_employee_no'), 'basis_fte', ['employee_no'], unique=False)
    op.create_index(op.f('ix_basis_fte_location'), 'basis_fte', ['location'], unique=False)
    op.create_index(op.f('ix_basis_fte_period'), 'basis_fte', ['period'], unique=False)
    op.create_table('basis_logic',
    sa.Column('account_code', sa.String(length=50), nullable=True),
    sa.Column('account_name', sa.String(length=200), nullable=True),
    sa.Column('pc', sa.String(length=200), nullable=True),
    sa.Column('distribution', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basis_logic_account_code'), 'basis_logic', ['account_code'], unique=False)
    op.create_index(op.f('ix_basis_logic_account_name'), 'basis_logic', ['account_name'], unique=False)
    op.create_index(op.f('ix_basis_logic_distribution'), 'basis_logic', ['distribution'], unique=False)
    op.create_index(op.f('ix_basis_logic_pc'), 'basis_logic', ['pc'], unique=False)
    op.create_index(op.f('ix_basis_logic_period'), 'basis_logic', ['period'], unique=False)
    op.create_table('basis_pc',
    sa.Column('dept_code', sa.String(length=50), nullable=True),
    sa.Column('dept', sa.String(length=200), nullable=True),
    sa.Column('div', sa.String(length=200), nullable=True),
    sa.Column('pc', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basis_pc_dept'), 'basis_pc', ['dept'], unique=False)
    op.create_index(op.f('ix_basis_pc_dept_code'), 'basis_pc', ['dept_code'], unique=False)
    op.create_index(op.f('ix_basis_pc_pc'), 'basis_pc', ['pc'], unique=False)
    op.create_index(op.f('ix_basis_pc_period'), 'basis_pc', ['period'], unique=False)
    op.create_table('basis_rev',
    sa.Column('div', sa.String(length=200), nullable=True),
    sa.Column('pc', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pct_certification_services', sa.Numeric(precision=18, scale=9), nullable=True),
    sa.Column('pct_ho', sa.Numeric(precision=18, scale=9), nullable=True),
    sa.Column('pct_all', sa.Numeric(precision=18, scale=9), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basis_rev_div'), 'basis_rev', ['div'], unique=False)
    op.create_index(op.f('ix_basis_rev_period'), 'basis_rev', ['period'], unique=False)
    op.add_column('distribution', sa.Column('period', sa.String(length=7), nullable=True))
    op.create_index(op.f('ix_distribution_period'), 'distribution', ['period'], unique=False)
    op.add_column('distribution_run', sa.Column('period', sa.String(length=7), nullable=True))
    op.create_index(op.f('ix_distribution_run_period'), 'distribution_run', ['period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_distribution_run_period'), table_name='distribution_run')
    op.drop_column('distribution_run', 'period')
    op.drop_index(op.f('ix_distribution_period'), table_name='distribution')
    op.drop_column('distribution', 'period')
    op.drop_index(op.f('ix_basis_rev_period'), table_name='basis_rev')
    op.drop_index(op.f('ix_basis_rev_div'), table_name='basis_rev')
    op.drop_table('basis_rev')
    op.drop_index(op.f('ix_basis_pc_period'), table_name='basis_pc')
    op.drop_index(op.f('ix_basis_pc_pc'), table_name='basis_pc')
    op.drop_index(op.f('ix_basis_pc_dept_code'), table_name='basis_pc')
    op.drop_index(op.f('ix_basis_pc_dept'), table_name='basis_pc')
    op.drop_table('basis_pc')
    op.drop_index(op.f('ix_basis_logic_period'), table_name='basis_logic')
    op.drop_index(op.f('ix_basis_logic_pc'), table_name='basis_logic')
    op.drop_index(op.f('ix_basis_logic_distribution'), table_name='basis_logic')
    op.drop_index(op.f('ix_basis_logic_account_name'), table_name='basis_logic')
    op.drop_index(op.f('ix_basis_logic_account_code'), table_name='basis_logic')
    op.drop_table('basis_logic')
    op.drop_index(op.f('ix_basis_fte_period'), table_name='basis_fte')
    op.drop_index(op.f('ix_basis_fte_location'), table_name='basis_fte')
    op.drop_index(op.f('ix_basis_fte_employee_no'), table_name='basis_fte')
    op.drop_index(op.f('ix_basis_fte_dept'), table_name='basis_fte')
    op.drop_table('basis_fte')
    op.drop_index(op.f('ix_basis_coa_period'), table_name='basis_coa')
    op.drop_index(op.f('ix_basis_coa_code'), table_name='basis_coa')
    op.drop_table('basis_coa')
    op.drop_index(op.f('ix_basis_allocation_period'), table_name='basis_allocation')
    op.drop_index(op.f('ix_basis_allocation_new_dept'), table_name='basis_allocation')
    op.drop_index(op.f('ix_basis_allocation_distribution'), table_name='basis_allocation')
    op.drop_index(op.f('ix_basis_allocation_account_name'), table_name='basis_allocation')
    op.drop_table('basis_allocation')
    # ### end Alembic commands ###
