[alembic]
script_location = alembic/source
sqlalchemy.url = mysql+mysqlconnector://%(SOURCE_DB_USER)s:%(SOURCE_DB_PASSWORD)s@%(SOURCE_DB_HOST)s:%(SOURCE_DB_PORT)s/%(SOURCE_DB_NAME)s

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
