"""add etl_state watermark table

Revision ID: 0862dc36029c
Revises: 4b48483a00ad
Create Date: 2026-07-07 10:14:36.595562
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0862dc36029c'
down_revision: Union[str, None] = '4b48483a00ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# NOTE: coa is an external reference table (not mapped by our models); the
# autogenerated `op.drop_table('coa')` is intentionally removed here.


def upgrade() -> None:
    op.create_table('etl_state',
    sa.Column('state_key', sa.String(length=100), nullable=False),
    sa.Column('watermark', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('state_key')
    )


def downgrade() -> None:
    op.drop_table('etl_state')
