"""initiate_finance

Revision ID: 3d42737c1cc6
Revises: 
Create Date: 2026-03-25 20:32:32.184763
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d42737c1cc6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_in',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('ref_no', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('project', sa.String(length=200), nullable=True),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('realization', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=True),
    sa.Column('coa_name', sa.String(length=200), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('source_line_id', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_line_id', name='uq_cash_in_source_line')
    )
    op.create_index(op.f('ix_cash_in_account_code'), 'cash_in', ['account_code'], unique=False)
    op.create_index(op.f('ix_cash_in_contact'), 'cash_in', ['contact'], unique=False)
    op.create_index(op.f('ix_cash_in_created_at'), 'cash_in', ['created_at'], unique=False)
    op.create_index(op.f('ix_cash_in_date'), 'cash_in', ['date'], unique=False)
    op.create_index(op.f('ix_cash_in_department'), 'cash_in', ['department'], unique=False)
    op.create_index(op.f('ix_cash_in_project'), 'cash_in', ['project'], unique=False)
    op.create_index(op.f('ix_cash_in_ref_no'), 'cash_in', ['ref_no'], unique=False)
    op.create_index(op.f('ix_cash_in_source_id'), 'cash_in', ['source_id'], unique=False)
    op.create_index(op.f('ix_cash_in_source_line_id'), 'cash_in', ['source_line_id'], unique=False)
    op.create_index(op.f('ix_cash_in_status'), 'cash_in', ['status'], unique=False)
    op.create_index(op.f('ix_cash_in_type'), 'cash_in', ['type'], unique=False)
    op.create_table('cash_out',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('ref_no', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('project', sa.String(length=200), nullable=True),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('realization', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=True),
    sa.Column('coa_name', sa.String(length=200), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('source_line_id', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_line_id', name='uq_cash_out_source_line')
    )
    op.create_index(op.f('ix_cash_out_account_code'), 'cash_out', ['account_code'], unique=False)
    op.create_index(op.f('ix_cash_out_contact'), 'cash_out', ['contact'], unique=False)
    op.create_index(op.f('ix_cash_out_created_at'), 'cash_out', ['created_at'], unique=False)
    op.create_index(op.f('ix_cash_out_date'), 'cash_out', ['date'], unique=False)
    op.create_index(op.f('ix_cash_out_department'), 'cash_out', ['department'], unique=False)
    op.create_index(op.f('ix_cash_out_project'), 'cash_out', ['project'], unique=False)
    op.create_index(op.f('ix_cash_out_ref_no'), 'cash_out', ['ref_no'], unique=False)
    op.create_index(op.f('ix_cash_out_source_id'), 'cash_out', ['source_id'], unique=False)
    op.create_index(op.f('ix_cash_out_source_line_id'), 'cash_out', ['source_line_id'], unique=False)
    op.create_index(op.f('ix_cash_out_status'), 'cash_out', ['status'], unique=False)
    op.create_index(op.f('ix_cash_out_type'), 'cash_out', ['type'], unique=False)
    op.create_table('manual_journal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('ref_no', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('project', sa.String(length=200), nullable=True),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('realization', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=True),
    sa.Column('coa_name', sa.String(length=200), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('source_line_id', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_line_id', name='uq_manual_journal_source_line')
    )
    op.create_index(op.f('ix_manual_journal_account_code'), 'manual_journal', ['account_code'], unique=False)
    op.create_index(op.f('ix_manual_journal_contact'), 'manual_journal', ['contact'], unique=False)
    op.create_index(op.f('ix_manual_journal_created_at'), 'manual_journal', ['created_at'], unique=False)
    op.create_index(op.f('ix_manual_journal_date'), 'manual_journal', ['date'], unique=False)
    op.create_index(op.f('ix_manual_journal_department'), 'manual_journal', ['department'], unique=False)
    op.create_index(op.f('ix_manual_journal_project'), 'manual_journal', ['project'], unique=False)
    op.create_index(op.f('ix_manual_journal_ref_no'), 'manual_journal', ['ref_no'], unique=False)
    op.create_index(op.f('ix_manual_journal_source_id'), 'manual_journal', ['source_id'], unique=False)
    op.create_index(op.f('ix_manual_journal_source_line_id'), 'manual_journal', ['source_line_id'], unique=False)
    op.create_index(op.f('ix_manual_journal_status'), 'manual_journal', ['status'], unique=False)
    op.create_index(op.f('ix_manual_journal_type'), 'manual_journal', ['type'], unique=False)
    op.create_table('payable_payment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('ref_no', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('project', sa.String(length=200), nullable=True),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('realization', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=True),
    sa.Column('coa_name', sa.String(length=200), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('source_line_id', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('purchase_ref_no', sa.String(length=100), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_line_id', 'purchase_ref_no', name='uq_payable_payment_source_line')
    )
    op.create_index(op.f('ix_payable_payment_account_code'), 'payable_payment', ['account_code'], unique=False)
    op.create_index(op.f('ix_payable_payment_contact'), 'payable_payment', ['contact'], unique=False)
    op.create_index(op.f('ix_payable_payment_created_at'), 'payable_payment', ['created_at'], unique=False)
    op.create_index(op.f('ix_payable_payment_date'), 'payable_payment', ['date'], unique=False)
    op.create_index(op.f('ix_payable_payment_department'), 'payable_payment', ['department'], unique=False)
    op.create_index(op.f('ix_payable_payment_project'), 'payable_payment', ['project'], unique=False)
    op.create_index(op.f('ix_payable_payment_purchase_date'), 'payable_payment', ['purchase_date'], unique=False)
    op.create_index(op.f('ix_payable_payment_purchase_id'), 'payable_payment', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_payable_payment_purchase_ref_no'), 'payable_payment', ['purchase_ref_no'], unique=False)
    op.create_index(op.f('ix_payable_payment_ref_no'), 'payable_payment', ['ref_no'], unique=False)
    op.create_index(op.f('ix_payable_payment_source_id'), 'payable_payment', ['source_id'], unique=False)
    op.create_index(op.f('ix_payable_payment_source_line_id'), 'payable_payment', ['source_line_id'], unique=False)
    op.create_index(op.f('ix_payable_payment_status'), 'payable_payment', ['status'], unique=False)
    op.create_index(op.f('ix_payable_payment_type'), 'payable_payment', ['type'], unique=False)
    op.create_table('purchase_invoice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('ref_no', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('project', sa.String(length=200), nullable=True),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('realization', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=True),
    sa.Column('coa_name', sa.String(length=200), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('source_line_id', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_line_id', name='uq_purchase_invoice_source_line')
    )
    op.create_index(op.f('ix_purchase_invoice_account_code'), 'purchase_invoice', ['account_code'], unique=False)
    op.create_index(op.f('ix_purchase_invoice_contact'), 'purchase_invoice', ['contact'], unique=False)
    op.create_index(op.f('ix_purchase_invoice_created_at'), 'purchase_invoice', ['created_at'], unique=False)
    op.create_index(op.f('ix_purchase_invoice_date'), 'purchase_invoice', ['date'], unique=False)
    op.create_index(op.f('ix_purchase_invoice_department'), 'purchase_invoice', ['department'], unique=False)
    op.create_index(op.f('ix_purchase_invoice_project'), 'purchase_invoice', ['project'], unique=False)
    op.create_index(op.f('ix_purchase_invoice_ref_no'), 'purchase_invoice', ['ref_no'], unique=False)
    op.create_index(op.f('ix_purchase_invoice_source_id'), 'purchase_invoice', ['source_id'], unique=False)
    op.create_index(op.f('ix_purchase_invoice_source_line_id'), 'purchase_invoice', ['source_line_id'], unique=False)
    op.create_index(op.f('ix_purchase_invoice_status'), 'purchase_invoice', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_invoice_type'), 'purchase_invoice', ['type'], unique=False)
    op.create_table('purchase_return',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('ref_no', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('project', sa.String(length=200), nullable=True),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('realization', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=True),
    sa.Column('coa_name', sa.String(length=200), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('source_line_id', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('purchase_ref_no', sa.String(length=100), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_line_id', name='uq_purchase_return_source_line')
    )
    op.create_index(op.f('ix_purchase_return_account_code'), 'purchase_return', ['account_code'], unique=False)
    op.create_index(op.f('ix_purchase_return_contact'), 'purchase_return', ['contact'], unique=False)
    op.create_index(op.f('ix_purchase_return_created_at'), 'purchase_return', ['created_at'], unique=False)
    op.create_index(op.f('ix_purchase_return_date'), 'purchase_return', ['date'], unique=False)
    op.create_index(op.f('ix_purchase_return_department'), 'purchase_return', ['department'], unique=False)
    op.create_index(op.f('ix_purchase_return_project'), 'purchase_return', ['project'], unique=False)
    op.create_index(op.f('ix_purchase_return_purchase_date'), 'purchase_return', ['purchase_date'], unique=False)
    op.create_index(op.f('ix_purchase_return_purchase_id'), 'purchase_return', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_purchase_return_purchase_ref_no'), 'purchase_return', ['purchase_ref_no'], unique=False)
    op.create_index(op.f('ix_purchase_return_ref_no'), 'purchase_return', ['ref_no'], unique=False)
    op.create_index(op.f('ix_purchase_return_source_id'), 'purchase_return', ['source_id'], unique=False)
    op.create_index(op.f('ix_purchase_return_source_line_id'), 'purchase_return', ['source_line_id'], unique=False)
    op.create_index(op.f('ix_purchase_return_status'), 'purchase_return', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_return_type'), 'purchase_return', ['type'], unique=False)
    op.create_table('receivable_payment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('ref_no', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('project', sa.String(length=200), nullable=True),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('realization', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=True),
    sa.Column('coa_name', sa.String(length=200), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('source_line_id', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('sales_ref_no', sa.String(length=100), nullable=True),
    sa.Column('sales_date', sa.Date(), nullable=True),
    sa.Column('sales_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_line_id', 'sales_ref_no', name='uq_receivable_payment_source_line')
    )
    op.create_index(op.f('ix_receivable_payment_account_code'), 'receivable_payment', ['account_code'], unique=False)
    op.create_index(op.f('ix_receivable_payment_contact'), 'receivable_payment', ['contact'], unique=False)
    op.create_index(op.f('ix_receivable_payment_created_at'), 'receivable_payment', ['created_at'], unique=False)
    op.create_index(op.f('ix_receivable_payment_date'), 'receivable_payment', ['date'], unique=False)
    op.create_index(op.f('ix_receivable_payment_department'), 'receivable_payment', ['department'], unique=False)
    op.create_index(op.f('ix_receivable_payment_project'), 'receivable_payment', ['project'], unique=False)
    op.create_index(op.f('ix_receivable_payment_ref_no'), 'receivable_payment', ['ref_no'], unique=False)
    op.create_index(op.f('ix_receivable_payment_sales_date'), 'receivable_payment', ['sales_date'], unique=False)
    op.create_index(op.f('ix_receivable_payment_sales_id'), 'receivable_payment', ['sales_id'], unique=False)
    op.create_index(op.f('ix_receivable_payment_sales_ref_no'), 'receivable_payment', ['sales_ref_no'], unique=False)
    op.create_index(op.f('ix_receivable_payment_source_id'), 'receivable_payment', ['source_id'], unique=False)
    op.create_index(op.f('ix_receivable_payment_source_line_id'), 'receivable_payment', ['source_line_id'], unique=False)
    op.create_index(op.f('ix_receivable_payment_status'), 'receivable_payment', ['status'], unique=False)
    op.create_index(op.f('ix_receivable_payment_type'), 'receivable_payment', ['type'], unique=False)
    op.create_table('sales_invoice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('ref_no', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('project', sa.String(length=200), nullable=True),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('realization', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=True),
    sa.Column('coa_name', sa.String(length=200), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('source_line_id', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_line_id', name='uq_sales_invoice_source_line')
    )
    op.create_index(op.f('ix_sales_invoice_account_code'), 'sales_invoice', ['account_code'], unique=False)
    op.create_index(op.f('ix_sales_invoice_contact'), 'sales_invoice', ['contact'], unique=False)
    op.create_index(op.f('ix_sales_invoice_created_at'), 'sales_invoice', ['created_at'], unique=False)
    op.create_index(op.f('ix_sales_invoice_date'), 'sales_invoice', ['date'], unique=False)
    op.create_index(op.f('ix_sales_invoice_department'), 'sales_invoice', ['department'], unique=False)
    op.create_index(op.f('ix_sales_invoice_project'), 'sales_invoice', ['project'], unique=False)
    op.create_index(op.f('ix_sales_invoice_ref_no'), 'sales_invoice', ['ref_no'], unique=False)
    op.create_index(op.f('ix_sales_invoice_source_id'), 'sales_invoice', ['source_id'], unique=False)
    op.create_index(op.f('ix_sales_invoice_source_line_id'), 'sales_invoice', ['source_line_id'], unique=False)
    op.create_index(op.f('ix_sales_invoice_status'), 'sales_invoice', ['status'], unique=False)
    op.create_index(op.f('ix_sales_invoice_type'), 'sales_invoice', ['type'], unique=False)
    op.create_table('sales_return',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('ref_no', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('project', sa.String(length=200), nullable=True),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('realization', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=True),
    sa.Column('coa_name', sa.String(length=200), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('source_line_id', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('sales_ref_no', sa.String(length=100), nullable=True),
    sa.Column('sales_date', sa.Date(), nullable=True),
    sa.Column('sales_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_line_id', name='uq_sales_return_source_line')
    )
    op.create_index(op.f('ix_sales_return_account_code'), 'sales_return', ['account_code'], unique=False)
    op.create_index(op.f('ix_sales_return_contact'), 'sales_return', ['contact'], unique=False)
    op.create_index(op.f('ix_sales_return_created_at'), 'sales_return', ['created_at'], unique=False)
    op.create_index(op.f('ix_sales_return_date'), 'sales_return', ['date'], unique=False)
    op.create_index(op.f('ix_sales_return_department'), 'sales_return', ['department'], unique=False)
    op.create_index(op.f('ix_sales_return_project'), 'sales_return', ['project'], unique=False)
    op.create_index(op.f('ix_sales_return_ref_no'), 'sales_return', ['ref_no'], unique=False)
    op.create_index(op.f('ix_sales_return_sales_date'), 'sales_return', ['sales_date'], unique=False)
    op.create_index(op.f('ix_sales_return_sales_id'), 'sales_return', ['sales_id'], unique=False)
    op.create_index(op.f('ix_sales_return_sales_ref_no'), 'sales_return', ['sales_ref_no'], unique=False)
    op.create_index(op.f('ix_sales_return_source_id'), 'sales_return', ['source_id'], unique=False)
    op.create_index(op.f('ix_sales_return_source_line_id'), 'sales_return', ['source_line_id'], unique=False)
    op.create_index(op.f('ix_sales_return_status'), 'sales_return', ['status'], unique=False)
    op.create_index(op.f('ix_sales_return_type'), 'sales_return', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_return_type'), table_name='sales_return')
    op.drop_index(op.f('ix_sales_return_status'), table_name='sales_return')
    op.drop_index(op.f('ix_sales_return_source_line_id'), table_name='sales_return')
    op.drop_index(op.f('ix_sales_return_source_id'), table_name='sales_return')
    op.drop_index(op.f('ix_sales_return_sales_ref_no'), table_name='sales_return')
    op.drop_index(op.f('ix_sales_return_sales_id'), table_name='sales_return')
    op.drop_index(op.f('ix_sales_return_sales_date'), table_name='sales_return')
    op.drop_index(op.f('ix_sales_return_ref_no'), table_name='sales_return')
    op.drop_index(op.f('ix_sales_return_project'), table_name='sales_return')
    op.drop_index(op.f('ix_sales_return_department'), table_name='sales_return')
    op.drop_index(op.f('ix_sales_return_date'), table_name='sales_return')
    op.drop_index(op.f('ix_sales_return_created_at'), table_name='sales_return')
    op.drop_index(op.f('ix_sales_return_contact'), table_name='sales_return')
    op.drop_index(op.f('ix_sales_return_account_code'), table_name='sales_return')
    op.drop_table('sales_return')
    op.drop_index(op.f('ix_sales_invoice_type'), table_name='sales_invoice')
    op.drop_index(op.f('ix_sales_invoice_status'), table_name='sales_invoice')
    op.drop_index(op.f('ix_sales_invoice_source_line_id'), table_name='sales_invoice')
    op.drop_index(op.f('ix_sales_invoice_source_id'), table_name='sales_invoice')
    op.drop_index(op.f('ix_sales_invoice_ref_no'), table_name='sales_invoice')
    op.drop_index(op.f('ix_sales_invoice_project'), table_name='sales_invoice')
    op.drop_index(op.f('ix_sales_invoice_department'), table_name='sales_invoice')
    op.drop_index(op.f('ix_sales_invoice_date'), table_name='sales_invoice')
    op.drop_index(op.f('ix_sales_invoice_created_at'), table_name='sales_invoice')
    op.drop_index(op.f('ix_sales_invoice_contact'), table_name='sales_invoice')
    op.drop_index(op.f('ix_sales_invoice_account_code'), table_name='sales_invoice')
    op.drop_table('sales_invoice')
    op.drop_index(op.f('ix_receivable_payment_type'), table_name='receivable_payment')
    op.drop_index(op.f('ix_receivable_payment_status'), table_name='receivable_payment')
    op.drop_index(op.f('ix_receivable_payment_source_line_id'), table_name='receivable_payment')
    op.drop_index(op.f('ix_receivable_payment_source_id'), table_name='receivable_payment')
    op.drop_index(op.f('ix_receivable_payment_sales_ref_no'), table_name='receivable_payment')
    op.drop_index(op.f('ix_receivable_payment_sales_id'), table_name='receivable_payment')
    op.drop_index(op.f('ix_receivable_payment_sales_date'), table_name='receivable_payment')
    op.drop_index(op.f('ix_receivable_payment_ref_no'), table_name='receivable_payment')
    op.drop_index(op.f('ix_receivable_payment_project'), table_name='receivable_payment')
    op.drop_index(op.f('ix_receivable_payment_department'), table_name='receivable_payment')
    op.drop_index(op.f('ix_receivable_payment_date'), table_name='receivable_payment')
    op.drop_index(op.f('ix_receivable_payment_created_at'), table_name='receivable_payment')
    op.drop_index(op.f('ix_receivable_payment_contact'), table_name='receivable_payment')
    op.drop_index(op.f('ix_receivable_payment_account_code'), table_name='receivable_payment')
    op.drop_table('receivable_payment')
    op.drop_index(op.f('ix_purchase_return_type'), table_name='purchase_return')
    op.drop_index(op.f('ix_purchase_return_status'), table_name='purchase_return')
    op.drop_index(op.f('ix_purchase_return_source_line_id'), table_name='purchase_return')
    op.drop_index(op.f('ix_purchase_return_source_id'), table_name='purchase_return')
    op.drop_index(op.f('ix_purchase_return_ref_no'), table_name='purchase_return')
    op.drop_index(op.f('ix_purchase_return_purchase_ref_no'), table_name='purchase_return')
    op.drop_index(op.f('ix_purchase_return_purchase_id'), table_name='purchase_return')
    op.drop_index(op.f('ix_purchase_return_purchase_date'), table_name='purchase_return')
    op.drop_index(op.f('ix_purchase_return_project'), table_name='purchase_return')
    op.drop_index(op.f('ix_purchase_return_department'), table_name='purchase_return')
    op.drop_index(op.f('ix_purchase_return_date'), table_name='purchase_return')
    op.drop_index(op.f('ix_purchase_return_created_at'), table_name='purchase_return')
    op.drop_index(op.f('ix_purchase_return_contact'), table_name='purchase_return')
    op.drop_index(op.f('ix_purchase_return_account_code'), table_name='purchase_return')
    op.drop_table('purchase_return')
    op.drop_index(op.f('ix_purchase_invoice_type'), table_name='purchase_invoice')
    op.drop_index(op.f('ix_purchase_invoice_status'), table_name='purchase_invoice')
    op.drop_index(op.f('ix_purchase_invoice_source_line_id'), table_name='purchase_invoice')
    op.drop_index(op.f('ix_purchase_invoice_source_id'), table_name='purchase_invoice')
    op.drop_index(op.f('ix_purchase_invoice_ref_no'), table_name='purchase_invoice')
    op.drop_index(op.f('ix_purchase_invoice_project'), table_name='purchase_invoice')
    op.drop_index(op.f('ix_purchase_invoice_department'), table_name='purchase_invoice')
    op.drop_index(op.f('ix_purchase_invoice_date'), table_name='purchase_invoice')
    op.drop_index(op.f('ix_purchase_invoice_created_at'), table_name='purchase_invoice')
    op.drop_index(op.f('ix_purchase_invoice_contact'), table_name='purchase_invoice')
    op.drop_index(op.f('ix_purchase_invoice_account_code'), table_name='purchase_invoice')
    op.drop_table('purchase_invoice')
    op.drop_index(op.f('ix_payable_payment_type'), table_name='payable_payment')
    op.drop_index(op.f('ix_payable_payment_status'), table_name='payable_payment')
    op.drop_index(op.f('ix_payable_payment_source_line_id'), table_name='payable_payment')
    op.drop_index(op.f('ix_payable_payment_source_id'), table_name='payable_payment')
    op.drop_index(op.f('ix_payable_payment_ref_no'), table_name='payable_payment')
    op.drop_index(op.f('ix_payable_payment_purchase_ref_no'), table_name='payable_payment')
    op.drop_index(op.f('ix_payable_payment_purchase_id'), table_name='payable_payment')
    op.drop_index(op.f('ix_payable_payment_purchase_date'), table_name='payable_payment')
    op.drop_index(op.f('ix_payable_payment_project'), table_name='payable_payment')
    op.drop_index(op.f('ix_payable_payment_department'), table_name='payable_payment')
    op.drop_index(op.f('ix_payable_payment_date'), table_name='payable_payment')
    op.drop_index(op.f('ix_payable_payment_created_at'), table_name='payable_payment')
    op.drop_index(op.f('ix_payable_payment_contact'), table_name='payable_payment')
    op.drop_index(op.f('ix_payable_payment_account_code'), table_name='payable_payment')
    op.drop_table('payable_payment')
    op.drop_index(op.f('ix_manual_journal_type'), table_name='manual_journal')
    op.drop_index(op.f('ix_manual_journal_status'), table_name='manual_journal')
    op.drop_index(op.f('ix_manual_journal_source_line_id'), table_name='manual_journal')
    op.drop_index(op.f('ix_manual_journal_source_id'), table_name='manual_journal')
    op.drop_index(op.f('ix_manual_journal_ref_no'), table_name='manual_journal')
    op.drop_index(op.f('ix_manual_journal_project'), table_name='manual_journal')
    op.drop_index(op.f('ix_manual_journal_department'), table_name='manual_journal')
    op.drop_index(op.f('ix_manual_journal_date'), table_name='manual_journal')
    op.drop_index(op.f('ix_manual_journal_created_at'), table_name='manual_journal')
    op.drop_index(op.f('ix_manual_journal_contact'), table_name='manual_journal')
    op.drop_index(op.f('ix_manual_journal_account_code'), table_name='manual_journal')
    op.drop_table('manual_journal')
    op.drop_index(op.f('ix_cash_out_type'), table_name='cash_out')
    op.drop_index(op.f('ix_cash_out_status'), table_name='cash_out')
    op.drop_index(op.f('ix_cash_out_source_line_id'), table_name='cash_out')
    op.drop_index(op.f('ix_cash_out_source_id'), table_name='cash_out')
    op.drop_index(op.f('ix_cash_out_ref_no'), table_name='cash_out')
    op.drop_index(op.f('ix_cash_out_project'), table_name='cash_out')
    op.drop_index(op.f('ix_cash_out_department'), table_name='cash_out')
    op.drop_index(op.f('ix_cash_out_date'), table_name='cash_out')
    op.drop_index(op.f('ix_cash_out_created_at'), table_name='cash_out')
    op.drop_index(op.f('ix_cash_out_contact'), table_name='cash_out')
    op.drop_index(op.f('ix_cash_out_account_code'), table_name='cash_out')
    op.drop_table('cash_out')
    op.drop_index(op.f('ix_cash_in_type'), table_name='cash_in')
    op.drop_index(op.f('ix_cash_in_status'), table_name='cash_in')
    op.drop_index(op.f('ix_cash_in_source_line_id'), table_name='cash_in')
    op.drop_index(op.f('ix_cash_in_source_id'), table_name='cash_in')
    op.drop_index(op.f('ix_cash_in_ref_no'), table_name='cash_in')
    op.drop_index(op.f('ix_cash_in_project'), table_name='cash_in')
    op.drop_index(op.f('ix_cash_in_department'), table_name='cash_in')
    op.drop_index(op.f('ix_cash_in_date'), table_name='cash_in')
    op.drop_index(op.f('ix_cash_in_created_at'), table_name='cash_in')
    op.drop_index(op.f('ix_cash_in_contact'), table_name='cash_in')
    op.drop_index(op.f('ix_cash_in_account_code'), table_name='cash_in')
    op.drop_table('cash_in')
    # ### end Alembic commands ###
