"""add unified gl general ledger table

Revision ID: f3811479c72a
Revises: 3d42737c1cc6
Create Date: 2026-07-06 10:24:33.678222
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3811479c72a'
down_revision: Union[str, None] = '3d42737c1cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('ref_key', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('ref_no', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('project', sa.String(length=200), nullable=True),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('realization', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=True),
    sa.Column('coa_name', sa.String(length=200), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('source_line_id', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'source_id', 'source_line_id', 'ref_key', name='uq_gl_type_source_line')
    )
    op.create_index(op.f('ix_gl_account_code'), 'gl', ['account_code'], unique=False)
    op.create_index(op.f('ix_gl_contact'), 'gl', ['contact'], unique=False)
    op.create_index(op.f('ix_gl_created_at'), 'gl', ['created_at'], unique=False)
    op.create_index(op.f('ix_gl_date'), 'gl', ['date'], unique=False)
    op.create_index(op.f('ix_gl_department'), 'gl', ['department'], unique=False)
    op.create_index(op.f('ix_gl_module'), 'gl', ['module'], unique=False)
    op.create_index(op.f('ix_gl_project'), 'gl', ['project'], unique=False)
    op.create_index(op.f('ix_gl_ref_no'), 'gl', ['ref_no'], unique=False)
    op.create_index(op.f('ix_gl_source_id'), 'gl', ['source_id'], unique=False)
    op.create_index(op.f('ix_gl_source_line_id'), 'gl', ['source_line_id'], unique=False)
    op.create_index(op.f('ix_gl_status'), 'gl', ['status'], unique=False)
    op.create_index(op.f('ix_gl_type'), 'gl', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gl_type'), table_name='gl')
    op.drop_index(op.f('ix_gl_status'), table_name='gl')
    op.drop_index(op.f('ix_gl_source_line_id'), table_name='gl')
    op.drop_index(op.f('ix_gl_source_id'), table_name='gl')
    op.drop_index(op.f('ix_gl_ref_no'), table_name='gl')
    op.drop_index(op.f('ix_gl_project'), table_name='gl')
    op.drop_index(op.f('ix_gl_module'), table_name='gl')
    op.drop_index(op.f('ix_gl_department'), table_name='gl')
    op.drop_index(op.f('ix_gl_date'), table_name='gl')
    op.drop_index(op.f('ix_gl_created_at'), table_name='gl')
    op.drop_index(op.f('ix_gl_contact'), table_name='gl')
    op.drop_index(op.f('ix_gl_account_code'), table_name='gl')
    op.drop_table('gl')
    # ### end Alembic commands ###
